workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: stable
      xcode: latest
      vars:
        SUPABASE_ANON_KEY: $SUPABASE_ANON_KEY
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign \
            --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
      - name: Build Android
        script: |
          flutter build apk --release \
            --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY \
            --dart-define=ENABLE_ADS=false
    artifacts:
      - build/ios/iphoneos/*.app
      - build/app/outputs/flutter-apk/*.apk
