import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class OnboardingScreen extends StatefulWidget {
  const OnboardingScreen({super.key, required this.initialLanguage});
  final String? initialLanguage;

  @override
  State<OnboardingScreen> createState() => _OnboardingScreenState();
}

class _OnboardingScreenState extends State<OnboardingScreen> {
  final _controller = PageController();
  int _page = 0;

  bool get _isEn => widget.initialLanguage == 'en';

  static const _pages = [
    _PageData(
      emoji: '🔮',
      gradientColors: [Color(0xFF4F46E5), Color(0xFF7C3AED)],
      titleZh: '星座今日運勢',
      titleEn: "Today's Horoscope",
      descZh: '每日更新的 AI 星座運勢\n解讀你的愛情、事業、健康運\n以及今日幸運色與幸運數字',
      descEn: 'Daily AI-powered horoscope readings\nDiscover your love, career & health fortune\nPlus your lucky color and number',
    ),
    _PageData(
      emoji: '✨',
      gradientColors: [Color(0xFF7C3AED), Color(0xFFC026D3)],
      titleZh: '智慧穿搭顧問',
      titleEn: 'Smart Outfit Advisor',
      descZh: '根據你的星座、身形、場合\nAI 為你量身打造專屬穿搭建議\n讓你每天都自信出門',
      descEn: 'Personalized outfit suggestions based on\nyour zodiac, body type & occasion\nLook great every day',
    ),
    _PageData(
      emoji: '⚠️',
      gradientColors: [Color(0xFF1E3A5F), Color(0xFF0F3460)],
      titleZh: '使用前請注意',
      titleEn: 'Before You Start',
      descZh: '本 App 所有內容（星座運勢、穿搭建議）均由 AI 人工智慧生成，僅供娛樂參考，不代表任何專業建議。\n\n請勿將 AI 建議作為醫療、財務或其他重大決策的依據。',
      descEn: 'All content in this App (horoscopes, outfit suggestions) is generated by AI for entertainment purposes only and does not represent professional advice.\n\nPlease do not rely on AI suggestions for medical, financial, or other important decisions.',
    ),
  ];

  Future<void> _onConfirm() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('onboarding_done', true);
    if (!mounted) return;
    Navigator.pushReplacementNamed(
      context,
      widget.initialLanguage == null ? '/language' : '/home',
      arguments: widget.initialLanguage,
    );
  }

  void _next() {
    if (_page < _pages.length - 1) {
      _controller.nextPage(
        duration: const Duration(milliseconds: 350),
        curve: Curves.easeInOut,
      );
    }
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            colors: [Color(0xFF1A1A2E), Color(0xFF16213E), Color(0xFF0F3460)],
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
          ),
        ),
        child: SafeArea(
          child: Column(
            children: [
              // Skip button
              Align(
                alignment: Alignment.topRight,
                child: Padding(
                  padding: const EdgeInsets.only(top: 12, right: 20),
                  child: _page < _pages.length - 1
                      ? TextButton(
                          onPressed: () => _controller.jumpToPage(_pages.length - 1),
                          child: Text(
                            _isEn ? 'Skip' : '跳過',
                            style: TextStyle(
                                color: Colors.white.withValues(alpha: 0.45),
                                fontSize: 14),
                          ),
                        )
                      : const SizedBox(height: 40),
                ),
              ),

              // Pages
              Expanded(
                child: PageView.builder(
                  controller: _controller,
                  onPageChanged: (i) => setState(() => _page = i),
                  itemCount: _pages.length,
                  itemBuilder: (context, i) =>
                      _OnboardingPage(data: _pages[i], isEn: _isEn),
                ),
              ),

              // Dots
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 20),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: List.generate(_pages.length, (i) {
                    final active = i == _page;
                    return AnimatedContainer(
                      duration: const Duration(milliseconds: 250),
                      margin: const EdgeInsets.symmetric(horizontal: 4),
                      width: active ? 20 : 7,
                      height: 7,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(4),
                        color: active
                            ? const Color(0xFFA78BFA)
                            : Colors.white.withValues(alpha: 0.25),
                      ),
                    );
                  }),
                ),
              ),

              // Bottom button
              Padding(
                padding: const EdgeInsets.fromLTRB(24, 0, 24, 32),
                child: _page == _pages.length - 1
                    ? GestureDetector(
                        onTap: _onConfirm,
                        child: Container(
                          width: double.infinity,
                          padding: const EdgeInsets.symmetric(vertical: 16),
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(14),
                            gradient: const LinearGradient(
                              colors: [Color(0xFF4F46E5), Color(0xFF7C3AED)],
                            ),
                            boxShadow: [
                              BoxShadow(
                                color: const Color(0xFF4F46E5).withValues(alpha: 0.4),
                                blurRadius: 20,
                              ),
                            ],
                          ),
                          child: Text(
                            _isEn
                                ? '✅  I understand all suggestions are AI-generated'
                                : '✅  我明白所有建議均由 AI 產生',
                            textAlign: TextAlign.center,
                            style: const TextStyle(
                              fontSize: 15,
                              fontWeight: FontWeight.w700,
                              color: Colors.white,
                            ),
                          ),
                        ),
                      )
                    : GestureDetector(
                        onTap: _next,
                        child: Container(
                          width: double.infinity,
                          padding: const EdgeInsets.symmetric(vertical: 16),
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(14),
                            gradient: LinearGradient(
                              colors: _pages[_page].gradientColors,
                            ),
                          ),
                          child: Text(
                            _isEn ? 'Next →' : '下一頁 →',
                            textAlign: TextAlign.center,
                            style: const TextStyle(
                              fontSize: 17,
                              fontWeight: FontWeight.w700,
                              color: Colors.white,
                            ),
                          ),
                        ),
                      ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _OnboardingPage extends StatelessWidget {
  const _OnboardingPage({required this.data, required this.isEn});
  final _PageData data;
  final bool isEn;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 32),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Container(
            width: 110,
            height: 110,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              gradient: LinearGradient(
                colors: data.gradientColors
                    .map((c) => c.withValues(alpha: 0.3))
                    .toList(),
              ),
              border: Border.all(
                color: data.gradientColors.last.withValues(alpha: 0.5),
                width: 1.5,
              ),
            ),
            child: Center(
              child: Text(data.emoji,
                  style: const TextStyle(fontSize: 52)),
            ),
          ),
          const SizedBox(height: 32),
          ShaderMask(
            shaderCallback: (bounds) => LinearGradient(
              colors: data.gradientColors,
            ).createShader(bounds),
            child: Text(
              isEn ? data.titleEn : data.titleZh,
              style: const TextStyle(
                fontSize: 26,
                fontWeight: FontWeight.w800,
                color: Colors.white,
              ),
              textAlign: TextAlign.center,
            ),
          ),
          const SizedBox(height: 20),
          Text(
            isEn ? data.descEn : data.descZh,
            style: TextStyle(
              fontSize: 15,
              color: Colors.white.withValues(alpha: 0.7),
              height: 1.75,
            ),
            textAlign: TextAlign.center,
          ),
        ],
      ),
    );
  }
}

class _PageData {
  const _PageData({
    required this.emoji,
    required this.gradientColors,
    required this.titleZh,
    required this.titleEn,
    required this.descZh,
    required this.descEn,
  });
  final String emoji;
  final List<Color> gradientColors;
  final String titleZh;
  final String titleEn;
  final String descZh;
  final String descEn;
}
